os: osx
osx_image: xcode11.6
language: swift
script: xcodebuild -project Kiwix.xcodeproj -scheme "Kiwix for iOS" CODE_SIGN_IDENTITY="" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_REQUIRED="NO" CODE_SIGNING_ALLOWED="NO"
